# Usage:
#     conda env create --file conda_env.yaml
#     conda env update --file conda_env.yaml --prune
#     conda env remove -n cursbnr-py
name: cursbnr-py
channels:
  - conda-forge
dependencies:
  - python>=3.12,<3.13
  - suds
  - sqlite
  - ipython
  - numpy
  - numpy-financial
  - python-dateutil
  - pandas>=2.0
  - matplotlib
  - xarray
  - tk
  - jupyter
  - pyqt # <- can't be built on Raspberry Pi
  - pyqt-stubs
  - pyqtgraph
  - qtpy
  - ipywidgets>=8.0 # older VS Code didn't properly support 8.0
  - ipympl
  - tqdm
  #- rich
  - pip
  - pip:
    - termtables
